language: node_js
node_js: stable
script:
- yarn build
- yarn test
deploy:
  provider: s3
  access_key_id: AKIA2YC6WUAYPF2QNS4N
  secret_access_key:
    secure: dmiy5myytUlpdgMNMGQmHDExSyXWK8NmitvPA1mWWp1jXGT7zDeRooSHCG57d4MhWAg4OGr8Ro0pcJvwmq1+e23nFxEbB0hhHBpZqbUjvotMQFWqBDbxHJFGo4XUcYJGvKGmXoFsJZFGOSuexbDzFMP05dce68THGsAkU1pmVSgcVEhmhieXarIjFL84ugCnJ1psqpGfmYpVTj20jTqyw6PnRRl11ECxwd7j0Tdu6TWleEj+E33nHvhMp9xAq04yrkaXk4cyqsv7RuEBUrhdTCKvzzwjC9F2Jy4wH5biy1ljF4DsczzXc3jW3egtozBDClAOYL1+bd2y+W6JCiKy1ISEWRDY6dtPP0hE6LOnaVJkhEkaKXB7VK+qcOZ8E1Kd6hI0Bz44POQXTCDJLx3GTDruhSO7YC/lBmLo0NtyXPmYyc0M//jNrZRcknBT+Az8CbLvRcHKELNoAiFPfDZYuUE1ug+EzZGberQHLeO4mniHS0gLInYHZSgfy/CALu3E1yiFtrLZRuRrwpq/dSWw4ZgLM2hqQAkrc/SO/Y1GLktH8kijYa7v+ZZYBDbkOtYUi7/5UugvQGc2+Tq1nFBpNVgRiz9Mc0TRRusk3gIGd8g4C+NqO3YNGkq2cjrtT2PhrZlprMHUQyXaSZeU28mzvV/R+40glsF6s9o8nebHH+Y=
  bucket: alex-van-vliet-scores
  region: eu-west-3
  skip_cleanup: true
  local-dir: build
  acl: public_read
  on:
    repo: alex-van-vliet/scores
  edge:
    branch: s3-backward-compat
