language: node_js
node_js: stable
script:
- yarn build
- yarn test
before_deploy:
- rvm $(travis_internal_ruby) do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIA2YC6WUAYPF2QNS4N
  secret_access_key:
    secure: iFkgly+H6P89714KPROzkVKPiW01NyV9rt7h5QArxuaaipumZClDGLv3wXKP882WN9AwH3LIYOMUydJrA52ZzCuj4+bHUfsuhDCNfHA6eXTY470ngWNz3AY6V2kqscUfHkZyvhLhwil1UUhjxjvvrwgOSNs/S5x09FBaTaipa/6SVMnylSMQJKaIE3VkK2BycgrYvB2wMFOuVQ2kl8EhwPF8yCVdvZjx4bPGhhY35Ssydj0WkCATCdVKnfU8l4elTr0di4lS/2OYvXJ8U6oEHsjbw3dBFatpEVoPRc3GqZsn/gTaMfjllObI0NGN/ejS4bF/qyD2GOkc3yKriTLCxCx8bSoLtPCnnmivtqA+M+Vw/H9U+RYxGNhGaehm/4rCka9A8xior+kmlt+ZplZi7p8N3Rbk4xGuQFJ3ne8aJ1+BqAPK+2Z3Fk/lunU4AdnCBIuCViI8qiPAtumyoWVB/wWiauc8J8DsDTd4IKTW67O8ahmEnXtQW6GRdAvbY0h8Nbier5h1GmzfaMlY9bvZ0bCOnF3zGnyJOGxCjqkr1iBDjXFbT49Gj2enN2wtvZc0zHvEOXNytqemTakfrHKMfXVDr2/yFFkvqHAXSr5SZw0lAd1hRj7DJegkHQscPp66pEM463UR7TlIa97Xw1StgNbtcql75lD7hEOGXooatV8=
  bucket: alex-van-vliet-scores
  region: eu-west-3
  skip_cleanup: true
  local-dir: build
  acl: public_read
  on:
    repo: alex-van-vliet/scores
