language: node_js
node_js: stable
deploy:
  provider: s3
  access_key_id: AKIA2YC6WUAYK7JLYBMQ
  secret_access_key:
    secure: fn1u8mWWo9YRsxiN5/mjRjP3K43r8s6z80+UrFzmvcOEf5SbvLhAZlwApOhMnmcEcUwT4SccyD/3Mu4fn/fgwyTCtRVu9kTlbrdoTnXBt0v7bzn0PaWVoDZMXmfQDNJlUFHehkDGVWtpNzFo0FSX3VSTh2mPwXEpPLO9c7U2qkATu71YYN6P7/wXdA4FXl5hC42xFGxqOUZKIbHKxOlS+dCRkKhtZGzS+n2Z+5FdorMYAJhgFDFAiMk8ehAcX0dkf0FH7JXyA9sVkz7bF723mcoUq6XAq61Ki9Su7HMqzr/2iBKU6YuzVolvt6nJcMqPrLoUEgxgaisBnYBrQC0aFQ+wIFZ04kYlSEo5oB+fTwq45CP/Lr8cyzjEveSAf9mWH/qvEw17NidWdVCps+DXNKno33RKsk9haKX42EcMdbZfKlf6ZRVk3EL0lCBDoP7uvSRYUTjTMSy/0k3In49MqbPMHK1nWcJariYLK5H8H5pkQnZOm36PyGCsQarWrumBdMzcYZFKOStl6Istk1Xpx/iELqdSr0wpMTLx76wp0Heg0qGl4dISrVq/K6wVa33Dyq14Y+riSmqftKG6747KFopluYXAwjAWs0frvk30buij5+Iq8gsYdgqDguLHWO1qEfzBelIcVDTl2q5YVWQQS99b0oaGTvzZNwSUmA7QGXM=
  bucket: alex-van-vliet-scores
  local-dir: build
  acl: public_read
  on:
    repo: alex-van-vliet/scores
