language: node_js
node_js: stable
script:
- yarn build
- yarn test
before_deploy:
- rvm $(travis_internal_ruby) do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIA2YC6WUAYPF2QNS4N
  secret_access_key:
    secure: Vrh1NmEhe68bXeiwLTuWYIU67f0bPIcSyae2T5RH8LwvK6mGGcSXivemQzbSWBAsIbfzKVgLZRrhNbE+hpyyqVOu0mznIk0OFnoVTUZd1bvkmLFDANY1mK+6HONWuVFUTdkYpcgSFhXktvrDV/yT+Kcmr8CfMxJ48vKEZTomUuDR2SJt4Dg0o/pcKzLYCzatT633b4j0JbwRV+2Q9vaAkLSRp9KQEhEL2RGqvSnAsY5x/Rfd/GqrpVPGXMvNYFHCUCDNB3yp7mRpOQtkJgYt3VYEzXqBQeqVPqbq4a253r6TSecgj2YZyGPzRm9bChk/SCp8dbaqK4AzJELpNWOx/+dqNxzu+6gYcjubCzoa5/GTKHIyVRIyIuPqi4qk7MCh0Qh0jOATXLZ+ghzJUD720FU7dLSeWbD9006ozGgVHnri3akOhDoVEOJ4A0hjdrcQhRUW6mXUkQIlp4g2jn/c3GSuFeWFIX/STpqowItHZwkwyqoUtxXN93/JVk/j9Dpzb0oNw75aBCbIi08ff+TXFiDwjO62xhEVn0Aw6q4nkxdgGbusHnjyi8zObTk75tZJCBSV3AO2Va73ZRA8gjaRWHpxV+tf8F8f9FZvDEWJwp5JuuyBn+iOBXsRqFsr3ypqAlyHNnGxOT0s8cLVTm/mgtB8u1GJVgYO620Itwc4PPU=
  bucket: alex-van-vliet-scores
  region: eu-west-3
  skip_cleanup: true
  local-dir: build
  on:
    repo: alex-van-vliet/scores
