language: node_js
node_js: stable
script:
- yarn build
- yarn test
before_deploy:
- rvm $(travis_internal_ruby) do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIA2YC6WUAYPF2QNS4N
  secret_access_key:
    secure: YjwrO3/SY7MH/3DlIU1OPpFBppjGokq/qn/7JyYw58IHMbQW0yMM6F9OFhmi3mMKNKUyjzLtNNdUVrB7XdvX/R0EPvO3Pe5hGzf9QQg4ZcBM1XhcnoEvbiEIfZRwQ8gOGxr9zFmFcUX/uBA2clCi3Qlho7sSi1lNxSracwTA3ytdCYwhg4ui44qw4KKUf8P/gPz8Ll1aE7q6CNB36fRj06y/O2iFGo6DpVjpGVGb88VC0aT0LDQuj7UoPTr0LIIUKJEk/ugbSgJ0sxECD+cC6KkAR/YvlLM4ViqcySmNH9vxm6I/X66pBXZ10sw/aw/4+FTvdNqPluF9rHUBtsJTe5JVb3mrOGlk0j76sEqolEta8sGNmoI9rAJHHzM7YX9PyBTx/ju+AM6m7xO+1tLhVb9e0m0hM7NeEEFSGkqeIs4hQcRo0kO8reqLuDIyi0P2cBFJlD44lLgJfqRBQuYnQ+UPHdc+70/AlwFIbThXHj1qtXl7zDlh9zYlkVhkk8Njb0zX3EgP420scNSyrxyFEZG+cHjTNyvUdF7Lr2s+E0D3+S2HuwTw4ZQFDi6ToNLuR/Nz3enG8CScH/a93xST/Xjz0cYURqIrzYvmsDuwv/plUZPLkICdYyLbCgJZVc+cQ3Xyi6cum+Ac9F6a1SEy7iUsuhLoCZf0QySZHd4b7Pc=
  bucket: alex-van-vliet-scores
  region: eu-west-3
  skip_cleanup: true
  local-dir: build
  on:
    repo: alex-van-vliet/scores
