language: node_js
node_js: stable
script:
- yarn build
- yarn test
before_deploy:
- rvm $(travis_internal_ruby) do gem install aws-sdk -v 2.1.36
deploy:
  provider: s3
  access_key_id: AKIA2YC6WUAYPF2QNS4N
  secret_access_key:
    secure: L2jjaa9v9S5W0C1LipNwKs77G579Q8HpZzZrL7F9ur0jFdAmCv7D1C2PewwI6zXTF8AaJAYt80wpP6KUKZPQ+yvrK74j22EdC5iMub9gD60yBBF5h3+/+qirJnDDMcdqH/NYkziCRGgtg4gnBbJweKQeN+0WZ3Hz5rInOKumU4zb1Hu35fRXMPyHw4y9b+oN3rAYbE9TvSCZh8+b+mnOWS+5tawl9pLHkEYsSqx6pK4/4YWxrwSfKNSELv/fmrAPN+JaMBfTRYWXmIOupxO/mKbEZZLZkdkpQ0eWyzW5eKgym1I5VFC4MiGLSye0I0gAGLOw9VwuqRi0Sv4/JihebC5iJ9vhonXlBUHjnC+3M7FSokChFrVy4RmXn9G5FUGLcTpYuc/4VNpePPEunta8hyy3Rjs6/dmxlXcb2sbxF7zuVt5TOnffs4hmF7jIUhcQDRYAEafq1Hb7X0OnjLg9lLEs9luy7zo4cTzLjDE861peXUhdZ44yKZiwqbFGoyYNSCC2eGMDAIiMtGOeo+Ta/hHCeiGgOiKVO+8c8wymHER2c/XhgVCKFNcoQ2a2vpv11G61xknDY7xQyg3Az0nLJagxvQxnJc/BYVaIXikZS3D92FXQaFDlhMWv9+zXFbCyentYMVDfpUJxjMISKXc9iVWF8AEmUR7YbcQMVTyK4tk=
  bucket: alex-van-vliet-scores
  region: eu-west-3
  skip_cleanup: true
  local-dir: build
  on:
    repo: alex-van-vliet/scores
